### ISSUE TITLE
Add ability to get the logging level

### ISSUE THREAD

**Issue by jimbobbennett** [adafruit/Adafruit_CircuitPython_Logging#14]
It would be good to be able to get the logging level.

One use case is when configuring the logger of one component to share the same level as another.

For example, the miniMQTT library exposes a logger, so I'd like to set the level of that in some client code to be the level set by my application.

**Comment by ladyada** [comment]
heya does this match the cpython version? we want to make this ver a clean subset :)

**Comment by jimbobbennett** [comment]
Good point!

The cpython version has a [`getEffectiveLevel` method](https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1665) that does the same thing, albeit by walking the hierarchy of loggers. I've renamed the method in my PR to match this.

**Comment by kattni** [comment]
This was resolved. Thanks!
