### ISSUE TITLE
Cross-post from MiniMQTT: formatting bytearrays raises runtime error

### ISSUE THREAD

**Issue by dlizotte-uwo** [adafruit/Adafruit_CircuitPython_Logging#17]
Hello; I had opened an issue in Adafruit_CircuitPython_MiniMQTT because in that library, bytearrays are being passed to the logger with %x formatting and this causes a runtime error. My original issue is here: [https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/67](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/67)

@brentru requested that I open an issue here instead as it's happening in Adafruit_CircuitPython_Logging. I am not sure how/whether the logger should handle bytearrays. Thanks!

**Comment by tannewt** [comment]
I don't think it's up to logging to support formatting bytearrays. The `%` syntax is an implementation of the CPython syntax and it doesn't support bytearray formatting. Docs are here: https://docs.python.org/3/library/string.html#format-specification-mini-language

You'll need to format the bytearray yourself.

**Comment by dlizotte-uwo** [comment]
OK that makes sense. Thanks!
