### ISSUE TITLE
Make true CPython subset?

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Logging#27]
Now that the library is listed on PyPI, is it worth make this a true subset of the CPython `logging` module?  It would mean moving things around between files, I think a breaking change.  Happy to close if not.

**Comment by askpatrickw** [comment]
I believe that is the general goal for libraries. If the group agrees, I'm happy to provide manual testing when you get to it.

**Comment by ladyada** [comment]
@tekktrik just getting to this email now lol! what would have to break? we do use this library a few places, so just want to know what has to get updated post-fix

**Comment by tekktrik** [comment]
Here's a list with some comments:

- `level_for` should probably be private - I think it's only purpose is internal use anyway
- I think `PrintHandler` would become `StreamHandler` with the only `stream` allowable being the standard output
- `FileHandler` would move out of the current `extensions.py` and into `__init__.py`.  At that point this could turn back into a single `adafruit_logging.py` file
- Minor, but I do know `FileHandler` keeps it's stream open rather than using a context manager internally, but figured I'd mention it

I thiiiiiink that's everything.

**Comment by tekktrik** [comment]
Oh, in CPython `logging`, `FileHandler` inherits from `StreamHandler`.

**Comment by ladyada** [comment]
@tekktrik sounds good to me, if you're willing to make the updates!

**Comment by tekktrik** [comment]
Definitely!
