### ISSUE TITLE
allow multiple handlers

### ISSUE THREAD

**Issue by vladak** [adafruit/Adafruit_CircuitPython_Logging#43]
The code says only one handler is supported: https://github.com/adafruit/Adafruit_CircuitPython_Logging/blob/a67856d9aae8fff3d2e6dee8a5cdc6082061ef42/adafruit_logging.py#L298-L306 however does not say why.

Is this some hidden limitation or conscious implementation choice ?

I am asking because I'd like to implement a `MQTTHandler` (log by publishing MQTT messages) and use it in addition to the `StreamHandler` for my project (https://github.com/vladak/shield/issues/3).

**Comment by tekktrik** [comment]
I think this is an implementation choice from when the library was lighter, but if you'd like to submit a PR to use multiple handlers I think it'd be a welcome addition.  I don't think it would add too much overhead to add that support.
