### ISSUE TITLE
Example name requires updating to match repo name

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Logging#5]
The example is currently `logger_simpletest.py` and should be renamed to `logging_simpletest.py` to match the CircuitPython library standards.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by jimbobbennett** [comment]
@kattni - I was about to do this, but noticed it has already been done!

**Comment by FoamyGuy** [comment]
@jimbobbennett Thank you for your willingness to work on it and pointing out that it's complete already. If you are interested in tackling a different "good first issue" type small change, there is one here: https://github.com/adafruit/circuitpython-org/issues/454. If you want to work on that one I can help you if needed, feel free to ping me on that issue, or in the #help-with-circuitpython channel in the Adafruit discord.
