### ISSUE TITLE
Suggest adding flush() to the emit method in the FileHandler example

### ISSUE THREAD

**Issue by znjp** [adafruit/Adafruit_CircuitPython_Logging#57]
I had a lot of trouble logging to a file on the internal storage of a QTPY ESP32-S3. It turns out that unless the board cleanly rebooted (e.g. via supervisor.reboot()) nothing would appear in the log file. This meant, if the power went out I would see nothing in the log. I fixed this by adding an explicit call to self.stream.flush() in the emit method of the FileHandler class. 

I'm not 100% sure on what the ramifications of this will be, but it might be worth at least adding a comment to the example that a call to stream.write() does not guarantee the message is flushed to the file.

Thanks!

**Comment by FoamyGuy** [comment]
I believe this should be handled now. There is an flush() call that comes right after emit() in the FileHandler here: https://github.com/adafruit/Adafruit_CircuitPython_Logging/blob/af7b881d7834f95fb8e9088b0ba3b49bda5a8288/adafruit_logging.py#L335 

Feel free to re-open this if you are still seeing similar issues under the latest version.
